export const allDiagnoses = [
  "Diabetes",
  "Hypertension",
  "Asthma",
  "Cancer",
  "Migraine",
  "Flu",
  "Covid-19",
  "Tuberculosis",
  "Arthritis",
  "Allergy",
  "Heart Disease",
  "Pneumonia",
  "Depression",
  "Anxiety",
  "Thyroid",
  "Obesity",
  "Stroke",
  "Epilepsy",
  "Dengue",
  "Malaria",
  "Bronchitis",
  "Sinusitis",
  "Gastritis",
  "Peptic Ulcer",
  "Irritable Bowel Syndrome",
  "Crohn’s Disease",
  "Ulcerative Colitis",
  "Hepatitis A",
  "Hepatitis B",
  "Hepatitis C",
  "Cirrhosis",
  "Pancreatitis",
  "Kidney Stones",
  "Chronic Kidney Disease",
  "Urinary Tract Infection",
  "Prostate Enlargement",
  "Anemia",
  "Leukemia",
  "Lymphoma",
  "Multiple Sclerosis",
  "Parkinson’s Disease",
  "Alzheimer’s Disease",
  "Dementia",
  "Osteoporosis",
  "Scoliosis",
  "Back Pain",
  "Sciatica",
  "Fibromyalgia",
  "Psoriasis",
  "Eczema",
  "Acne",
  "Melanoma",
  "Glaucoma",
  "Cataract",
  "Macular Degeneration",
  "Otitis Media",
  "Hearing Loss",
  "Vertigo",
  "Sleep Apnea",
  "Insomnia",
  "Panic Disorder",
  "Bipolar Disorder",
  "Schizophrenia",
  "Eating Disorder",
  "GERD",
  "Appendicitis",
  "Gallstones",
  "Thrombosis",
  "Varicose Veins",
  "Sepsis",
  "Atherosclerosis",
  "Angina",
  "Myocardial Infarction",
  "Arrhythmia",
  "Heart Failure",
  "Pericarditis",
  "Endocarditis",
  "Cardiomyopathy",
  "Pulmonary Embolism",
  "Chronic Obstructive Pulmonary Disease",
  "Emphysema",
  "Pleural Effusion",
  "Lung Cancer",
  "Hyperthyroidism",
  "Hypothyroidism",
  "Cushing Syndrome",
  "Addison’s Disease",
  "Polycystic Ovary Syndrome",
  "Endometriosis",
  "Infertility",
  "Erectile Dysfunction",
  "Testicular Cancer",
  "Cervical Cancer",
  "Ovarian Cancer",
  "Breast Cancer",
  "Rheumatoid Arthritis",
  "Gout",
  "Lupus",
  "Vasculitis",
  "Sarcoidosis",
  "Tetanus",
  "Rabies",
  "Cholera",
  "Typhoid Fever",
  "Food Poisoning",
  "Norovirus Infection",
  "Rotavirus Infection",
  "Measles",
  "Mumps",
  "Rubella",
  "Chickenpox",
  "Shingles",
  "HIV/AIDS",
  "Syphilis",
  "Gonorrhea",
  "Chlamydia",
  "Pelvic Inflammatory Disease",
  "Hemorrhoids",
  "Anal Fissure",
  "Constipation",
];

export const allMedicines = [
  "Paracetamol",
  "Ibuprofen",
  "Aspirin",
  "Amoxicillin",
  "Azithromycin",
  "Ciprofloxacin",
  "Metformin",
  "Atorvastatin",
  "Omeprazole",
  "Pantoprazole",
  "Ranitidine",
  "Cetirizine",
  "Loratadine",
  "Levocetirizine",
  "Montelukast",
  "Salbutamol",
  "Budesonide",
  "Prednisone",
  "Dexamethasone",
  "Hydrocortisone",
  "Insulin",
  "Glimepiride",
  "Losartan",
  "Amlodipine",
  "Enalapril",
  "Telmisartan",
  "Clopidogrel",
  "Warfarin",
  "Heparin",
  "Digoxin",
  "Furosemide",
  "Spironolactone",
  "Hydrochlorothiazide",
  "Nitroglycerin",
  "Isosorbide Mononitrate",
  "Ondansetron",
  "Domperidone",
  "Metoclopramide",
  "Loperamide",
  "ORS",
  "Albendazole",
  "Mebendazole",
  "Fluconazole",
  "Ketoconazole",
  "Acyclovir",
  "Oseltamivir",
  "Linezolid",
  "Vancomycin",
  "Meropenem",
  "Ceftriaxone"
];
